from itops_env.server.mcp_servers.tools import tool_definitions, validate_registry

EXPECTED = {
    "list_applications",
    "get_application",
    "create_application",
    "update_application",
    "delete_application",
    "confirm_delete_application",
    "activate_application",
    "deactivate_application",
    "list_catalog_apps",
    "get_catalog_app",
    "install_oin_app",
    "list_brands",
    "get_brand",
    "create_brand",
    "replace_brand",
    "delete_brand",
    "list_brand_domains",
    "list_custom_domains",
    "create_custom_domain",
    "get_custom_domain",
    "replace_custom_domain",
    "delete_custom_domain",
    "upsert_custom_domain_certificate",
    "verify_custom_domain",
    "get_error_page_resources",
    "get_customized_error_page",
    "replace_customized_error_page",
    "delete_customized_error_page",
    "get_default_error_page",
    "get_preview_error_page",
    "replace_preview_error_page",
    "delete_preview_error_page",
    "get_sign_in_page_resources",
    "get_customized_sign_in_page",
    "replace_customized_sign_in_page",
    "delete_customized_sign_in_page",
    "get_default_sign_in_page",
    "get_preview_sign_in_page",
    "replace_preview_sign_in_page",
    "delete_preview_sign_in_page",
    "list_sign_in_widget_versions",
    "get_sign_out_page_settings",
    "replace_sign_out_page_settings",
    "list_email_templates",
    "get_email_template",
    "list_email_customizations",
    "create_email_customization",
    "get_email_customization",
    "replace_email_customization",
    "delete_email_customization",
    "delete_all_email_customizations",
    "get_email_customization_preview",
    "get_email_default_content",
    "get_email_default_content_preview",
    "get_email_settings",
    "replace_email_settings",
    "send_test_email",
    "list_email_domains",
    "create_email_domain",
    "get_email_domain",
    "replace_email_domain",
    "delete_email_domain",
    "verify_email_domain",
    "list_brand_themes",
    "get_brand_theme",
    "replace_brand_theme",
    "upload_brand_theme_logo",
    "delete_brand_theme_logo",
    "upload_brand_theme_favicon",
    "delete_brand_theme_favicon",
    "upload_brand_theme_background_image",
    "delete_brand_theme_background_image",
    "list_device_assurance_policies",
    "get_device_assurance_policy",
    "create_device_assurance_policy",
    "replace_device_assurance_policy",
    "delete_device_assurance_policy",
    "list_policies",
    "get_policy",
    "create_policy",
    "update_policy",
    "delete_policy",
    "activate_policy",
    "deactivate_policy",
    "list_policy_rules",
    "get_policy_rule",
    "create_policy_rule",
    "update_policy_rule",
    "delete_policy_rule",
    "activate_policy_rule",
    "deactivate_policy_rule",
    "get_login_failures",
    "get_logs",
    "list_users",
    "get_user_profile_attributes",
    "get_user",
    "create_user",
    "update_user",
    "deactivate_user",
    "delete_deactivated_user",
    "export_users_csv",
    "list_groups",
    "get_group",
    "create_group",
    "delete_group",
    "confirm_delete_group",
    "update_group",
    "list_group_users",
    "list_group_apps",
    "add_user_to_group",
    "remove_user_from_group",
    "list_user_groups",
}


def test_okta_identity_catalog_has_exact_public_tools_and_registry_handlers():
    validate_registry()
    assert set(tool_definitions("okta")) == EXPECTED
    schemas = tool_definitions("okta")
    assert (
        schemas["create_user"].parameters["properties"]["activate"]["default"] is True
    )
    assert schemas["list_users"].parameters["properties"]["search"]["default"] == ""
    assert "outputSchema" not in schemas["export_users_csv"].model_dump(by_alias=True)
