CREATE TABLE okta_applications (id TEXT PRIMARY KEY, data_json TEXT NOT NULL);
CREATE TABLE okta_catalog_apps (id TEXT PRIMARY KEY, data_json TEXT NOT NULL);
CREATE TABLE okta_policies (id TEXT PRIMARY KEY, data_json TEXT NOT NULL);
CREATE TABLE okta_device_policies (id TEXT PRIMARY KEY, data_json TEXT NOT NULL);
CREATE TABLE okta_log_events (id TEXT PRIMARY KEY, data_json TEXT NOT NULL);
CREATE TABLE okta_brands (id TEXT PRIMARY KEY, data_json TEXT NOT NULL);
CREATE TABLE okta_pages (brand_id TEXT NOT NULL REFERENCES okta_brands(id), kind TEXT NOT NULL, slot TEXT NOT NULL, data_json TEXT NOT NULL, PRIMARY KEY(brand_id,kind,slot));
CREATE TABLE okta_widget_versions (version TEXT PRIMARY KEY);
CREATE TABLE okta_email_template_defaults (name TEXT PRIMARY KEY, content_json TEXT NOT NULL);
INSERT INTO okta_email_template_defaults VALUES ('UserActivation', '{"en":{"subject":"Activate ${org.name} account","body":"Open ${activationLink}"}}');
CREATE TABLE okta_email_preview_values (name TEXT PRIMARY KEY, value TEXT NOT NULL);
INSERT INTO okta_email_preview_values VALUES ('org.name','OpsForge'), ('activationLink','https://example.test/activate');
CREATE TABLE okta_email_templates (brand_id TEXT NOT NULL REFERENCES okta_brands(id), name TEXT NOT NULL REFERENCES okta_email_template_defaults(name), settings_json TEXT NOT NULL, PRIMARY KEY(brand_id,name));
CREATE TABLE okta_email_customizations (id TEXT PRIMARY KEY, brand_id TEXT NOT NULL, template_name TEXT NOT NULL, data_json TEXT NOT NULL, FOREIGN KEY(brand_id,template_name) REFERENCES okta_email_templates(brand_id,name));
CREATE TABLE okta_email_outbox (id INTEGER PRIMARY KEY, brand_id TEXT NOT NULL, template_name TEXT NOT NULL, language TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, step INTEGER NOT NULL, clock INTEGER NOT NULL, FOREIGN KEY(brand_id,template_name) REFERENCES okta_email_templates(brand_id,name));
INSERT INTO okta_widget_versions VALUES ('7'), ('*');
CREATE TABLE okta_themes (id TEXT PRIMARY KEY, brand_id TEXT NOT NULL REFERENCES okta_brands(id), data_json TEXT NOT NULL);
CREATE TABLE okta_domains (id TEXT PRIMARY KEY, data_json TEXT NOT NULL, brand_id TEXT REFERENCES okta_brands(id));
CREATE TABLE okta_email_domains (id TEXT PRIMARY KEY, brand_id TEXT NOT NULL REFERENCES okta_brands(id), data_json TEXT NOT NULL);
CREATE TABLE okta_domain_certificates (domain_id TEXT PRIMARY KEY REFERENCES okta_domains(id), certificate TEXT NOT NULL, chain TEXT NOT NULL, private_key BLOB NOT NULL);
CREATE TABLE okta_policy_rules (id TEXT PRIMARY KEY, policy_id TEXT NOT NULL REFERENCES okta_policies(id) ON DELETE CASCADE, data_json TEXT NOT NULL);
INSERT INTO okta_catalog_apps VALUES ('bookmark', '{"name":"bookmark","displayName":"Bookmark","features":[],"signOnModes":["BOOKMARK"]}');
